name: docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docs
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
